function [filefilt,dataformats]=aedes_getfilefilter()
% AEDES_GETFILEFILTER - Get File Filter for uigetfile and aedes_juigetfiles
%   (this is a helper function)
%
% Synopsis: 
%       filefilt=aedes_data_read
%
% Description:
%       Returns the correct file filter for Aedes.
%
% Examples:
%
% See also:
%       AEDES, AEDES_DATA_READ

% This function is a part of Aedes - A graphical tool for analyzing 
% medical images
%
% Copyright (C) 2006 Juha-Pekka Niskanen <Juha-Pekka.Niskanen@uku.fi>
% 
% Department of Physics, Department of Neurobiology
% University of Kuopio, FINLAND
%
% This program may be used under the terms of the GNU General Public
% License version 2.0 as published by the Free Software Foundation
% and appearing in the file LICENSE.TXT included in the packaging of
% this program.
%
% This program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
% WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.


filefilt = {['fid;2dseq;*.hdr;*.nii;*.nii.gz;*.sur;',...
  '*.mri;*.dcm;',...
  '*.xxm;*.mat;*.t1r;*.s1r;*.fdf;*.sgl;',...
  '*.t2r;*.s2r;*.t1;*.t2;*.s1;*.s2;*.df;',...
  '*.sf;*.r2;*.b1;*.roi'],'All Supported Files';...
  'fid','Varian or Bruker FID-files (fid)';...
	'2dseq','Bruker reconstructed files (2dseq)';...
  '*.hdr;*.nii;*.nii.gz','NIfTI and Analyze 7.5 files (*.nii,*.nii.gz,*.hdr)';...
  '*.sur','S.M.I.S. Image files (*.sur)';...
  '*.mri','MRI-Files (*.mri)';...
  '*.dcm','DICOM image files (*.dcm)'; ...
  '*.hdr','SPECT/CT Header Files (*.hdr)';...
  '*.xxm','Reconstruction parameter file (*.xxm)';...
  '*.mat','Matlab MAT-Files (*.mat)';...
  '*.roi','Aedes ROI-Files (*.roi)';...
  '*.fdf','Varian FDF-Files (*.fdf)';...
  '*.sgl','SWIFT reconstruction files (*.sgl)';...
  '*.t1r','T1R-Files (*.t1r)';...
  '*.s1r','S1R-Files (*.s1r)';...
  '*.t2r','T2R-Files (*.t2r)';...
  '*.s2r','S2R-Files (*.s2r)';...
  '*.t1','T1-Files (*.t1)';...
  '*.t2','T2-Files (*.t2)';...
  '*.s1','S1-Files (*.s1)';...
  '*.s2','S2-Files (*.s2)';...
  '*.df','DF-Files (*.df)';...
  '*.sf','SF-Files (*.sf)';...
  '*.r2','R2-Files (*.r2)';...
  '*.b1','B1-Files (*.b1)';...
  '*.*', 'All Files (*.*)'};

dataformats = {'',...
  'vnmr',...
  'nifti',...
  'sur',...
  'mri',...
  'dcm',...
  'spect/ct',...
  'spect/ct',...
  'mat',...
  'roi',...
  'fdf',...
  'swift_sgl',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  'mri',...
  ''}';

% Uigetfile is broken in OSX version of Matlab (at least R2011a), and
% doesn't work with filters that are not file extensions (e.g. fid or
% 2dseq).
if ismac
	filefilt{1,1} = '*.*';
	filefilt{1,2} = 'All Files';
end

% - EOF -